Tamari gray/issue228
crowdleague/crowdleague pull request #241
Opened 2020-10-16 03:51 UTC by tamari-gray

fixes #228

2020-10-16 05:00 UTC, tamari-gray reviewed
think she gtg :)

2020-10-16 05:35 UTC, nickmeinhold requested changes
Awesome job mate!!! A few minor nits, just requesting comments in a few places really, code is really great - thanks heaps for making these improvements!

2020-10-16 05:35 UTC, nickmeinhold commented on lib/middleware/auth/sign_in_with_email.dart
> -          // set the UI to waiting
nice!

2020-10-16 05:35 UTC, nickmeinhold commented on lib/middleware/auth/sign_out_user.dart
great 👍

2020-10-16 05:35 UTC, nickmeinhold commented on lib/middleware/auth/sign_up_with_email.dart
> -          // set the UI to waiting
love it

2020-10-16 05:35 UTC, nickmeinhold commented on lib/services/auth_service.dart
> +  Stream<ReduxAction> emailSignInStream(String email, String password) async* {
much nicer - thanks!

2020-10-16 05:35 UTC, nickmeinhold commented on lib/services/auth_service.dart
> +  Stream<ReduxAction> emailSignUpStream(String email, String password) async* {
boom!

2020-10-16 05:35 UTC, nickmeinhold commented on lib/services/auth_service.dart
> -      await FirebaseAuth.instance.signOut();
Heck yeah! Thanks for making my code better!

2020-10-16 05:35 UTC, nickmeinhold commented on test/mocks/auth/firebase_auth_mocks.dart
> +class FakeFirebaseAuthSignInException extends Fake implements FirebaseAuth {
The name here is very specific and so I don't think needs any documentation

2020-10-16 05:35 UTC, nickmeinhold commented on test/mocks/auth/firebase_auth_mocks.dart
> +class FakeFirebaseAuthThrows extends Fake implements FirebaseAuth {
The name here is a bit more general so I think some commenting would be really helpful - is that OK?

2020-10-16 05:35 UTC, nickmeinhold commented on test/mocks/auth/firebase_auth_mocks.dart
>  class FakeFirebaseAuth1 extends Fake implements FirebaseAuth {
I know this wasn't commented before (that's my bad) but would you mind adding a brief comment that indicates what the class is for and how/where it's used?

2020-10-16 05:35 UTC, nickmeinhold commented on test/mocks/auth/google_signin_mocks.dart
> +
could you add to the class comment what has changed with the new code?

2020-10-16 05:35 UTC, nickmeinhold commented on test/mocks/mock_firebase_platform.dart
> +class MockFirebasePlatform extends Mock implements FirebasePlatform {}
I think it'd be great if we both got into the habit of commenting the classes we make in the mocks files - could you add a comment here?

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/middleware/auth/sign_in_with_email_middleware_test.dart
> -    test('on successfull sign with firebase, dispatches correct actions',
awesome!

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/middleware/auth/sign_in_with_email_middleware_test.dart
> -    test('on successfull sign with firebase, dispatches correct actions',
so much nice that way, thanks heaps!

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> -// TODO: test sign out - dispatches a StoreProblem action on error
you're a legend!  👋  TODOs... good riddance!

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +    Firebase.delegatePackingProperty = MockFirebasePlatform();
Ooooooh nice!  Now I get what the `MockFirebasePlatform` was for!

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +        'emailSignInStream catches firebaseAuthExceptions and emits StoreProblem actions',
I think StoreProblem should be AddProblem?

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +    test('emailSignInStream catches errors and emits StoreProblem actions',
StoreProblem -> AddProblem?

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +      /// Check that emailSignInStream emits addProblem action with info from caught error.
addProblem -> AddProblem (seems like a super nit but the meaning the case conveys here is worth caring about I reckon)

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +      // TODO: add apple sign in when #232 is completed. https://github.com/crowdleague/crowdleague/issues/232
grab me for a chat about this if you don't mind - I think I'd like to get use away from allowing TODOs in the dev branch

2020-10-16 05:35 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +    test(
super super nit - could you add a line b/w tests here? (whitespace)

2020-10-16 06:32 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +      // TODO: add apple sign in when #232 is completed. https://github.com/crowdleague/crowdleague/issues/232
I made [Style Guide > avoid-pushing-todos-to-dev](https://github.com/crowdleague/crowdleague/wiki/Style-Guide-(WIP)#avoid-pushing-todos-to-dev) and will add a note to discuss on Monday 🙂

2020-10-17 04:57 UTC, nickmeinhold commented on test/unit/services/auth_service_test.dart
> +      // TODO: add apple sign in when #232 is completed. https://github.com/crowdleague/crowdleague/issues/232
I've added an item to Monday standup

2020-10-17 05:08 UTC, nickmeinhold approved these changes
Really great work mate, thank you!

2020-10-17 05:13 UTC, merged