Refactor problem_utils and Problem creation
crowdleague/crowdleague pull request #297
Opened 2020-12-03 04:14 UTC by T-Davis

2020-12-03 04:38 UTC, tamari-gray approved these changes
woooh lgtm!

2020-12-03 05:02 UTC, nickmeinhold requested changes
Looks awesome mate!  I would happily approve but just had a couple of q's

2020-12-04 03:13 UTC, T-Davis commented on lib/utils/problem_utils.dart
> +        info: info == null ? null : BuiltMap(info),
You got it!
It took me a little bit to track down what was happening, but a runtime error it was. BuiltMap(null) is no good.

2020-12-04 03:32 UTC, T-Davis commented on lib/utils/problem_utils.dart
> +        message: error.toString(),
So good!
Fixed!

2020-12-04 08:26 UTC, nickmeinhold approved these changes
Beautiful work mate!!!

2020-12-04 08:27 UTC, merged